### ISSUE TITLE
Buildout error: Failed to get "sinar.templer" dependency

### ISSUE THREAD

**Issue by leowmjw** [Sinar/sinar.digimon#11]
When running buildout; unable to get the sinar.templer dependency:

**(virtualenv) vagrant@precise64:/vagrant$ ./bin/buildout 2>&1 |  tee buildout.log**

Output of **buildout.log**:

```
Download error on http://packages.sinarproject.org/packages/: [Errno -2] Name or servic
e not known -- Some packages may not be found!
--------------------------------------------------------------------------------
Downloading zc.buildout bootstrap.py file from:
  https://bootstrap.pypa.io/bootstrap-buildout.py
To:
  /vagrant/bootstrap-buildout.py
--------------------------------------------------------------------------------
mr.developer: Queued 'sinar.templer' for checkout.
mr.developer: Checkout URL for existing package 'sinar.templer' differs. Expected 'https://github.com/Sinar/sinar.templer.git'.
Develop: '/vagrant/.'
warning: no files found matching '*.txt'
warning: no files found matching '*.rst'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Develop: '/vagrant/dev/sinar.templer'
Traceback (most recent call last):
  File "/tmp/tmpimRKnN", line 13, in <module>
    with open('/vagrant/dev/sinar.templer/setup.py', 'U') as f:
IOError: [Errno 2] No such file or directory: '/vagrant/dev/sinar.templer/setup.py'
While:
  Installing.
  Processing develop directory '/vagrant/dev/sinar.templer'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/vagrant/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/vagrant/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/vagrant/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/vagrant/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 1020, in develop
    call_subprocess(args)
  File "/vagrant/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 160, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/home/vagrant/virtualenv/bin/python', '/tmp/tmpimRKnN', '-q', 'develop', '-mN', '-d', '/vagrant/develop-eggs/tmpcj1Hn9build'
```

**Comment by leowmjw** [comment]
Observed dev folder has sinar.templar but it is empty.

Work around for now:

```
$ cd dev
$ cd rm -rf sinar.templar
$ git clone https://github.com/Sinar/sinar.templer.git
$ cd -
$ ./bin/buildout
```

**Comment by leowmjw** [comment]
:+1: confirm it works
